### ISSUE TITLE
update readme to actually show what this tool does for me so i know whether to invest the time.

### ISSUE THREAD

**Issue by pieroway** [itemis/xtext-languageserver-example#11]

**Comment by cdietrich** [comment]
Hi is this about the repos readme or the extensions readme?

**Comment by pieroway** [comment]
both really.  i just now found your blog post at https://blogs.itemis.com/en/integrating-xtext-language-support-in-visual-studio-code which sheds some light on the extensions purpose, so i suggest adding a link to that at the very least. it would provide a quick understanding of what the extension does.
not to see if it will work for my purposes. thanks.
