### ISSUE TITLE
Remote debugging is no longer working

### ISSUE THREAD

**Issue by cdietrich** [itemis/xtext-languageserver-example#21]
Remote debugging is no longer working

it work only if i set an environment variable like

`export MYDSL_STANDALONE_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=y,quiet=y -Xmx256m"`

**Comment by cdietrich** [comment]
@franzbecker can you have a look. it looks like the gradle application plugin passes these as args and not as jvm params by default

**Comment by colameo** [comment]
another way todo this is to set the env variable in the extension itself:

var process = require('process');

export function activate(context: ExtensionContext) {
   ... 
    process.env['MYDSL_STANDALONE_OPTS'] = "-Dmyenv=foobar";

    // Create the language client and start the client.
    let disposable = new LanguageClient('Xtext Server', serverOptions, clientOptions).start();

**Comment by cdietrich** [comment]
Fixed
