### ISSUE TITLE
npm install fails - Need updated vscode version 1.25

### ISSUE THREAD

**Issue by pdigre** [itemis/xtext-languageserver-example#33]
Solution: in package.json update from version 1.22 to 1.25.

    "engines": {
        "vscode": "^1.25.0"
    },

**Comment by cdietrich** [comment]
can you please provide a PR

**Comment by pdigre** [comment]
What is a PR ?

**Comment by cdietrich** [comment]
pull request

**Comment by pdigre** [comment]
eh, are you onboarding me ;-)

**Comment by cdietrich** [comment]
Fixed with https://github.com/itemis/xtext-languageserver-example/pull/35

**Comment by cdietrich** [comment]
@pdigre could you please give it a try?
