### ISSUE TITLE
Failed to build the project following the instructions

### ISSUE THREAD

**Issue by wmanth** [itemis/xtext-languageserver-example#71]
### Command line

Environment: macOS Mojave
Java Version 1.8.0_201

I cloned the project and followed the instructions given in _README.md_
Calling `./gradlew startCode` in the project root directory on command line ends up with the error message:
```
0    [main] INFO  text.xtext.generator.XtextGenerator  - Initializing Xtext generator
5    [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Adding generated EPackage 'org.eclipse.xtext.common.types.TypesPackage'
59   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl at 'file:/Users/q188463/Projects/SoSA/Development/xtext-languageserver-example/org.xtext.example.mydsl/'
59   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.tests at 'file:/Users/q188463/Projects/SoSA/Development/xtext-languageserver-example/org.xtext.example.mydsl.tests/'
60   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Registering project org.xtext.example.mydsl.ide at 'file:/Users/q188463/Projects/SoSA/Development/xtext-languageserver-example/org.xtext.example.mydsl.ide/'
66   [main] INFO  lipse.emf.mwe.utils.StandaloneSetup  - Using resourceSet registry. The registered Packages will not be registered in the global EPackage.Registry.INSTANCE!
250  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/Xtext/Xbase/XAnnotations' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
252  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xtype' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
261  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/xbase/Xbase' from 'platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel'
261  [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://www.eclipse.org/xtext/common/JavaVMTypes' from 'platform:/resource/org.eclipse.xtext.common.types/model/JavaVMTypes.genmodel'
595  [main] INFO  erator.parser.antlr.AntlrToolFacade  - Downloading file from 'http://download.itemis.com/antlr-generator-3.2.0-patch.jar' ...
Downloading ANTLR parser generator failed: download.itemis.com
Please install the feature 'Xtext Antlr SDK' manually using the external updatesite:

                'http://download.itemis.com/updates/'.

(see http://www.eclipse.org/Xtext/download.html for details)
611  [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems running workflow org.xtext.example.mydsl.GenerateMyDsl: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
java.lang.RuntimeException: Problems running workflow org.xtext.example.mydsl.GenerateMyDsl: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:104)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:62)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:52)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.run(Mwe2Launcher.java:78)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher.main(Mwe2Launcher.java:36)
Caused by: java.lang.RuntimeException: 
[ERROR]: 

*ATTENTION*
It is highly recommended to use ANTLR's parser generator (get it from 'http://xtext.itemis.com/'). 
As an alternative to ANTLR you could also use the alternative implementation shipped with Xtext.
To do so use the generator fragment 'org.eclipse.xtext.generator.parser.packrat.PackratParserFragment' in your mwe2 file instead.(Element: -UNKNOWN-; Reported by: XtextGenerator)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.handleIssues(Mwe2Bridge.java:59)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.preInvoke(Mwe2Bridge.java:69)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.preInvoke(AbstractWorkflowComponent.java:207)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowComponent.preInvoke(AbstractCompositeWorkflowComponent.java:30)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:102)
        ... 4 more
```
 How can I install the Xtext Antlr SDK from an Eclipse update site on command line?

### Eclipse DSL Tools

Version: 2020-06 (4.16.0)
Build id: 20200416-1403

I installed _Xtext Antlr SDK_ from the given Itemis update site.
Importing the source tree as Gradle project into my Eclipse workspace gives me errors:
* org.xtext.example.mydsl
* org.xtext.example.mydsl.ide
* org.xtext.example.mydsl.tests

Description | Resource | Path | Location | Type
--- |--- | --- | --- | ---
AbstractMyDslIdeModule cannot be resolved to a type. | MyDslIdeModule.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide | line: 15 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend | Xtend Problem
AbstractMyDslRuntimeModule cannot be resolved to a type. | MyDslRuntimeModule.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl | line: 10 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDslRuntimeModule.xtend | Xtend Problem
AbstractMyDslScopeProvider cannot be resolved to a type. | MyDslScopeProvider.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/scoping | line: 13 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/scoping/MyDslScopeProvider.xtend | Xtend Problem
AbstractMyDslValidator cannot be resolved to a type. | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 15 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
Duplicate method _format(Object, IFormattableDocument) in type MyDslFormatter | MyDslFormatter.java | /org.xtext.example.mydsl/xtend-gen/org/xtext/example/mydsl/formatting2 | line 15 | Java Problem
Duplicate method _format(Object, IFormattableDocument) in type MyDslFormatter | MyDslFormatter.java | /org.xtext.example.mydsl/xtend-gen/org/xtext/example/mydsl/formatting2 | line 22 | Java Problem
Greeting cannot be resolved to a type. | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 14 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
Greeting cannot be resolved to a type. | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 19 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
Greeting cannot be resolved to a type. | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 20 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
Model cannot be resolved to a type. | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 13 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
Model cannot be resolved to a type. | MyDslParsingTest.xtend | /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests | line: 20 /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests/MyDslParsingTest.xtend | Xtend Problem
MyDslGrammarAccess cannot be resolved to a type. | MyDslIdeContentProposalProvider.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist | line: 14 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/MyDslIdeContentProposalProvider.xtend | Xtend Problem
MyDslStandaloneSetupGenerated cannot be resolved to a type. | MyDslStandaloneSetup.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl | line: 10 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDslStandaloneSetup.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.Greeting cannot be resolved to a type. | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 8 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.Greeting cannot be resolved to a type. | MyDslGenerator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator | line: 11 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.Greeting cannot be resolved to a type. | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 7 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.Model cannot be resolved to a type. | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 9 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.Model cannot be resolved to a type. | MyDslParsingTest.xtend | /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests | line: 13 /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests/MyDslParsingTest.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.MyDslPackage cannot be resolved to a type. | MyDslIdeContentProposalProvider.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist | line: 9 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/MyDslIdeContentProposalProvider.xtend | Xtend Problem
org.xtext.example.mydsl.myDsl.MyDslPackage cannot be resolved to a type. | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 8 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
org.xtext.example.mydsl.services.MyDslGrammarAccess cannot be resolved to a type. | MyDslIdeContentProposalProvider.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist | line: 10 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/MyDslIdeContentProposalProvider.xtend | Xtend Problem
Superclass must be a class | MyDslIdeModule.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide | line: 15 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend | Xtend Problem
Superclass must be a class | MyDslRuntimeModule.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl | line: 10 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDslRuntimeModule.xtend | Xtend Problem
Superclass must be a class | MyDslScopeProvider.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/scoping | line: 13 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/scoping/MyDslScopeProvider.xtend | Xtend Problem
Superclass must be a class | MyDslStandaloneSetup.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl | line: 10 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDslStandaloneSetup.xtend | Xtend Problem
Superclass must be a class | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 15 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
Syntax error on tokens, delete these tokens | MyDslParsingTest.java | /org.xtext.example.mydsl.tests/xtend-gen/org/xtext/example/mydsl/tests | line 14 | Java Problem
The field MyDslParsingTest.parseHelper refers to the missing type Model | MyDslParsingTest.xtend | /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests | line: 24 /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests/MyDslParsingTest.xtend | Xtend Problem
The method createInjector() of type MyDslIdeSetup must override a superclass method. | MyDslIdeSetup.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide | line: 16 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeSetup.xtend | Xtend Problem
The method createInjector() of type MyDslIdeSetup must override or implement a supertype method | MyDslIdeSetup.java | /org.xtext.example.mydsl.ide/xtend-gen/org/xtext/example/mydsl/ide | line 15 | Java Problem
The method createInjectorAndDoEMFRegistration() is undefined for the type MyDslStandaloneSetup | MyDslStandaloneSetup.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl | line: 13 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/MyDslStandaloneSetup.xtend | Xtend Problem
The method error(String, Object, String) is undefined | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 22 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
The method newLines(int) is undefined | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 20 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
The method or field from is undefined for the type EObject | MyDslGenerator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator | line: 27 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend | Xtend Problem
The method or field from is undefined for the type EObject | MyDslGenerator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator | line: 27 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend | Xtend Problem
The method or field Greeting is undefined | MyDslGenerator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator | line: 26 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend | Xtend Problem
The method or field greetingRule is undefined | MyDslIdeContentProposalProvider.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist | line: 20 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/MyDslIdeContentProposalProvider.xtend | Xtend Problem
The method or field MyDslInjectorProvider is undefined | MyDslParsingTest.xtend | /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests | line: 16 /org.xtext.example.mydsl.tests/src/org/xtext/example/mydsl/tests/MyDslParsingTest.xtend | Xtend Problem
The method or field MyDslPackage is undefined | MyDslIdeContentProposalProvider.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist | line: 21 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/MyDslIdeContentProposalProvider.xtend | Xtend Problem
The method or field MyDslPackage is undefined | MyDslValidator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation | line: 23 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/validation/MyDslValidator.xtend | Xtend Problem
The method or field name is undefined for the type EObject | MyDslGenerator.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator | line: 27 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend | Xtend Problem
The method or field newLine is undefined | MyDslFormatter.xtend | /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2 | line: 22 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/formatting2/MyDslFormatter.xtend | Xtend Problem
Type mismatch: cannot convert from MyDslIdeModule to Module | MyDslIdeSetup.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide | line: 17 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeSetup.xtend | Xtend Problem
Type mismatch: cannot convert from MyDslRuntimeModule to Module | MyDslIdeSetup.xtend | /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide | line: 17 /org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeSetup.xtend | Xtend Problem

**Comment by cdietrich** [comment]
Do you behind a proxy?

**Comment by cdietrich** [comment]
you should also be able to download the jar manually, 
store it as

`org.xtext.example.mydsl/.antlr-generator-3.2.0-patch.jar`

and restart the gradle command.

**Comment by wmanth** [comment]
You are right, trying on my private Mac things work fine - on command line as well as in Eclipse.
Seems, again some config tweaks are necessary in my work environment.

Thanks for pointing out!
