### ISSUE TITLE
Is this plugin still supported and recommended to use for LS DSL implementation for VsCode?

### ISSUE THREAD

**Issue by lidiapopescu** [itemis/xtext-languageserver-example#78]
I have few eclipse plugins generated with xtext for dsl languages and I need to implement same approach for VsCode.
Could you please recommend me what would be the best approach ?
Do we have a xtext plugin for vscode that could do same thing? generate a dsl language server based on a grammar ?
Thank you

**Comment by miklossy** [comment]
As a starting point you can take a look at the [LSP Support](https://www.eclipse.org/Xtext/documentation/340_lsp_support.html) chapter of the Xtext documentation.

**Comment by cdietrich** [comment]
i dont know of a vscode plugin that generates a stub for an xtext project

**Comment by kuniss** [comment]
You may have a look on my xtext editor vscode extension: https://github.com/kuniss/xtext-ide-extensions.
