### ISSUE TITLE
"Project and External Dependencies" disappeared in eclipse IDE

### ISSUE THREAD

**Issue by RobertWalterU3d** [itemis/xtext-languageserver-example#79]
I used this template in 2020 to build my own VS Code extension.

Everything worked back then, but when I open the workspace with the very same eclipse version again today (2020-06), the library "Project and External Dependencies" does not show and all the dependencies to Xtext and related libs are broken.

Building from gradle still works, and I assume the issue is related to how buildship sets up the classpath, but I tried to refresh the gradle project and get this "Library entry" back so I can use the eclipse IDE to browse my projects again, but I cannot make it work. Any ideas how I can fix that?

**Comment by cdietrich** [comment]
please check the gradle log / console on refresh gradle project

**Comment by RobertWalterU3d** [comment]
sorry, but where I can I find the gradle log/console? ALl I see are these two views in the IDE (which is where I do "RIght click->Gradle->Refresh Gradle Project"):

![image](https://user-images.githubusercontent.com/63954267/148761999-5f6f9dd4-79ee-4858-b1a1-58ac749feb3b.png)

**Comment by cdietrich** [comment]
in the console view on the error i see gradle operations when calling gradle refresh on parent/root
<img width="1765" alt="Bildschirmfoto 2022-01-10 um 12 55 52" src="https://user-images.githubusercontent.com/238736/148762275-bae9048b-ff17-4111-b5fe-2aa0ff7b790e.png">

**Comment by RobertWalterU3d** [comment]
I don't see that option, but it looks like the [Gradle Operations] are already "open"
![image](https://user-images.githubusercontent.com/63954267/148763040-e1ea7530-48a3-4aca-8ff6-f7993e8c6232.png)

When I perform the refresh, the console shows nothing.

**Comment by cdietrich** [comment]
there is no gradle -> refresh gradle project. ?!?

**Comment by RobertWalterU3d** [comment]
The menu option is there, but the console does not show anything when I perform the action.

**Comment by RobertWalterU3d** [comment]
![gradleConsole](https://user-images.githubusercontent.com/63954267/148765676-194eb436-04b6-432a-a916-716401837ad8.gif)

**Comment by cdietrich** [comment]
is there anything in error log?

**Comment by RobertWalterU3d** [comment]
This is how the classpath file looks like for the language project:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" output="bin/main" path="src">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="src-gen">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/main" path="xtend-gen">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer"/>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```

Again, nothing that would normally be in the "Project and External Dependencies" can be resolved, so my Problems view looks like below (but I guess you mean something else with "error log", right?)

![image](https://user-images.githubusercontent.com/63954267/148770327-5b001d05-333c-4a0c-960b-c158566576d7.png)

**Comment by cdietrich** [comment]
yes and normally gradle logs that in the operations log if it cannot resolve stuff.
maybe its also a java version 
+ gradle version + buildship version + eclipse version problem.

which ones do you use?

**Comment by RobertWalterU3d** [comment]
When I run gradle from console to refresh dependencies, it works (I use the build task as target, maybe that is not correct?)

![image](https://user-images.githubusercontent.com/63954267/148770552-2147a438-07e3-4858-b6ef-ee3146e79728.png)

**Comment by cdietrich** [comment]
yes but buildship should do the same.

**Comment by RobertWalterU3d** [comment]
so, this is what I see at the end of the log file:

![image](https://user-images.githubusercontent.com/63954267/148770987-aa51e419-ac04-42a7-8802-3da7ea716a4c.png)

**Comment by cdietrich** [comment]
so it looks like there is something wrong with your setup.

**Comment by RobertWalterU3d** [comment]
Maybe unsurprisingly, still wanted to share, this folder is empty:

`.\.metadata\.plugins\org.eclipse.buildship.core\project-preferences\`

I understand that buildship should store something there.

I will check the versions of gradle, buildship, etc, next, as you suggested.

**Comment by cdietrich** [comment]
are you sure the eclipse workspace and the gradle root or a project root are disjoint?

**Comment by RobertWalterU3d** [comment]
eclipse version is: 2020-06
buildship version (acc. to eclipse->Help->About): 4.1.4.v20200326-1743
gradle (acc to command ./gradlew -v): 5.6.4

> Are you sure the eclipse workspace and the gradle root or a project root are disjoint?

How can I ensure that? Again, building from command line and starting VS code with the plugin works just fine...


The interesting thing is that I used the very same eclipse, gradle, buildship version in 2020 to develop this language extension... so I wonder how it could have worked back then but not today...

**Comment by cdietrich** [comment]
what is the dir of your eclipse workspace

**Comment by RobertWalterU3d** [comment]
I use the exact same folder structure as this example repository does, so I have a a root folder where my language/ide/websocket/vscode-extension projects are all located in separate folder.

The settings.gradle file includes these five projects.

**Comment by kuniss** [comment]
In the meantime jcenter went down. Maybe, this is the reason? That's where the dependencies are resolved from...Am 10.01.2022 14:15 schrieb RobertWalterU3d ***@***.***>:
eclipse version is: 2020-06
buildship version (acc. to eclipse->Help->About): 4.1.4.v20200326-1743
gradle (acc to command ./gradlew -v): 5.6.4

Are you sure the eclipse workspace and the gradle root or a project root are disjoint?

How can I ensure that? Again, building from command line and starting VS code with the plugin works just fine...
The interesting thing is that I used the very same eclipse, gradle, buildship version in 2020 to develop this language extension... so I wonder how it could have worked back then but not today...

**Comment by cdietrich** [comment]
again which is the workspace dir you use in eclipse?

**Comment by kuniss** [comment]
... use mavenCentral() instead.Am 10.01.2022 14:18 schrieb Denis Kuniß ***@***.***>:In the meantime jcenter went down. Maybe, this is the reason? That's where the dependencies are resolved from...Am 10.01.2022 14:15 schrieb RobertWalterU3d ***@***.***>:
eclipse version is: 2020-06
buildship version (acc. to eclipse->Help->About): 4.1.4.v20200326-1743
gradle (acc to command ./gradlew -v): 5.6.4

Are you sure the eclipse workspace and the gradle root or a project root are disjoint?

How can I ensure that? Again, building from command line and starting VS code with the plugin works just fine...
The interesting thing is that I used the very same eclipse, gradle, buildship version in 2020 to develop this language extension... so I wonder how it could have worked back then but not today...

**Comment by RobertWalterU3d** [comment]
It is the "root":

`D:\dev\repository\root\`

Inside this root folder, there are the five projects, and `gradlew.bat`, `.metadata`, `.settings` and such.

**Comment by cdietrich** [comment]
then this is something that buildship dislikes. can you try different dir.

**Comment by cdietrich** [comment]
just new workspace and use gradle import on the root

**Comment by RobertWalterU3d** [comment]
> ... use mavenCentral() instead

Sorry, I'm not used to gradle, maven, or eclipse, I just try to used this as a template, so I don't know how I would go about using maven central instead. It also looks like as if all the dependencies are cached in `~\.gradle\caches\modules-2\` ... so I think it is not an issue of resolving the dependencies from server...?

**Comment by RobertWalterU3d** [comment]
> just new workspace and use gradle import on the root

I'm sorry, I don't follow. When I create a new workspace, it is empty, right? So, I'm not sure

* what files I need to copy into the new workspace, if any
* where to run gradle import from, if the workspace is empty

I'm reall ynot familiar with any of these technologies, sorry.

**Comment by cdietrich** [comment]
create new workspace (empty)
import -> gradle -> existing gradle project
choose the root

**Comment by RobertWalterU3d** [comment]
Wow, that did indeed fix it!

**Comment by RobertWalterU3d** [comment]
Thank you very much, I would have never guessed that.
