### ISSUE TITLE
Debugging language server remotely

### ISSUE THREAD

**Issue by RobertWalterU3d** [itemis/xtext-languageserver-example#82]
I see that in the extension.ts file, the debug server options are set up to start the server with remote debug configured.
Can somebody please explain to me how I can utilize this and actually debug my language server?

I'm trying to extend the LanguageServerImpl cause I want to react when the `didChangeWatchedFiles` message is sent, but I don't seem to receive a message in my language server.

**Comment by cdietrich** [comment]
pelase check the startup script created by gradle.
i asusme code in extension ts is old/outdated/unrelated

**Comment by RobertWalterU3d** [comment]
Thanks. I am not sure what "socket mode" would be. Are you referring to something like this: https://github.com/itemis/xtext-languageserver-example/blob/master/vscode-extension/src/extension.ts ?

If yes, would that mean that I would need to also change gradle to launch the client differently from the RunServer type?

There are several startup scripts, `my.namespace.mydsl.ide.bat`, `mydsl-socket.bat`, `mydsl-standalone.bat`
They all use %XXX_OPTS% amongst others when running java, but I don't see where to set this property... I could set it manually, I guess.

So, is my understanding correct that [this function](https://github.com/itemis/xtext-languageserver-example/blob/eb164955658df4e05bf69fba91599f63fbe1ac6d/vscode-extension-self-contained/src/extension.ts#L51)   is not having any effect?

**Comment by RobertWalterU3d** [comment]
> i usually write a delegae message consumer here
> return result;
> instead of returning the original one.
> you might be able to do the same for the io server

Sorry, I am not following why a delegate like this would be needed and where I would put it, not sure what "io server" means.

**Comment by cdietrich** [comment]
result =  new MessageConsumer() {consume(message m){ consumer.conume(m)}}

**Comment by cdietrich** [comment]
language servers can task to client via
java socket
process io
websocket

**Comment by cdietrich** [comment]
i dont know how the api that calls the gralde script from typescript set the options or not.
you would need to alter the script and debug

**Comment by cdietrich** [comment]
when i debug `RunServer `with the `vscode-extension`(this one uses socket) then i see didwatch called

**Comment by cdietrich** [comment]
=> how did you customize the languageserverimpl

**Comment by RobertWalterU3d** [comment]
I might have just misunderstood when this message is sent. It is send when the user changes what file is opened or in viewport, or when exactly?

```
public class MyDslLanguageServer extends LanguageServerImpl {

	private static final Logger LOG = Logger.getLogger(LanguageServerImpl.class);
	@Override
	public void didChangeWatchedFiles(DidChangeWatchedFilesParams params) {
		super.didChangeWatchedFiles(params);
		// trying to log some message here
	}
} 
```

**Comment by RobertWalterU3d** [comment]
Okay, my original understanding was that this message is sent when the "watched" files change, i.e. if a file of extension ".mydsl" is  edited in the client. Reading the spec again, I think my original understanding is correct. So, that is actually what I would like to be notified about in my server.
Also, can I configure what files my extension is watching?

**Comment by cdietrich** [comment]
i guess this is something to ask in the languageserverprotocol and or vscode languageclient repo.
i dont get the edited point.
edits you will get notfied with didChange

i dont know what your debugging problem is. cant you simply edit the script and hard code remote debugging there? (or use the socket client + server as proposed, started in debug mode from eclipse (or idea))
i have no idea where you exactly are stuck
