### ISSUE TITLE
Connecting to external Xtext LSP server from VSCode extension

### ISSUE THREAD

**Issue by ipa-hsd** [itemis/xtext-languageserver-example#91]
I have created a Xtext LSP project similar to https://github.com/itemis/xtext-languageserver-example/tree/master/org.xtext.example.mydsl and I am using the jar in a VSCode extension

```js
    var serverInfo = function () {
        // Connect to the language server via a io channel
        var jar = context.asAbsolutePath(path.join('resources', 'dsl-ls.jar'));
        var child = spawn('java', ['-Xdebug', '-Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n,quiet=y', '-jar', jar, '-log debug']);
        console.log(child.stdout.toString());
        child.stdout.on('data', function (chunk) {
            console.log(chunk.toString());
        });
        child.stderr.on('data', function (chunk) {
            console.error(chunk.toString());
        });
        return Promise.resolve(child);
    };
    var clientOptions = {
        documentSelector: ['mydsl']
    };
    // Create the language client and start the client.
    client = new LanguageClient('MYDSL1', serverInfo, clientOptions);
```
This method works quite well. But I want to debug my server on the console, so I started the server on the terminal
```bash
java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n,quiet=y -jar ./mydsl-ls.jar -log debug
```
which is basically the same command in `spawn`.

And I made changes in `extension.ts` as per
https://github.com/itemis/xtext-languageserver-example/blob/dfbb365d70e1370db4d4b60bc193efa173082266/vscode-extension/src/extension.ts#L13-L24

But I get an error on the extension  output terminal without any additional info:
```
 Connection to server is erroring. Shutting down server.
```
Firstly, how do I know what port the LSP server is running on? If port is not the issue, what else might be the problem?

**Comment by cdietrich** [comment]
this wont work. if you want to start outside you need to start server in socket mode and connect via socket from client 

https://github.com/itemis/xtext-languageserver-example/blob/dfbb365d70e1370db4d4b60bc193efa173082266/vscode-extension/src/extension.ts#L17
https://github.com/itemis/xtext-languageserver-example/blob/master/org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/RunServer.java

**Comment by ipa-hsd** [comment]
Great! Thanks for the example code. It works as expected. 
For future reference: I had to add additional deps - io.github.classgraph, com.google.gson and aopalliance
